### PR TITLE
This is a major overhaul and a replacement of pretty much the whole codebase.

### PR DESCRIPTION
**Pull request by fschaeck**
…odebase.

This version 2.0 is now fully object oriented and fully compatible to
GNU sed v4.8 with all it's bells and whissles.

The only things not implemented are character classes (no support in
Python regex) and the command e (might still come in a later update).

The case-modifying escapes \L, \l, \U, \u and \E in the replacement
string are now supported as well.

The GNU sed v4.8 documentation can be used as a reference for pythonsed.

All testcase - except the two for character classes and command e -
are passing now.

Testcases for the new commands v,R and W have been added as well as
a test script (test_script_inplace.py) to test the in-place editiing.

I also added the possibility to use the much more powerful Python
syntax for the regex in addresses and s command by specifying the
-p or --python-syntax option.

Note the different handling of empty matches in those cases, depending
on the Python version and if -p is used or not...

I decided to create a pull request against this repository instead of creating a new project PythonSed2, since it doesn't serve anyone having two different implementations of the same thing.

### CODE REVIEW

**Comment by fschaeck** [comment]
Ups.... I guess I forgot to check the code against Python 2.7.
I will do the necessary re-work and commit the required fixes soon.

**Comment by GillesArcas** [comment]
Hi Frank,

great job! You have pushed it much farther than I did. I have run the tests, checked with pep8 and pylint and tried to get relevant timings. I have not much time for the moment (working on another of my projects) and I did not get all the results I wanted. Nothing to not accept the request unless perhaps some stylistic remarks. Standard guidelines advise to put spaces around operators and to avoid parentheses when they are not necessary (tests and function results). Also, it would be better to remove all trailing spaces as they can lead to a lot of diffs.

However... Giving the job you have done and the time spent, I feel it would be more logical for you to be the main maintainer and for your repo to be the main one. I will link to your repository from mine and forward any PR to you if any. Is it OK for you?

I plan to take the time to analyze your code. I guess it will be very interesting and that I can learn a lot from it.

Gilles

**Comment by fschaeck** [comment]
Hi Gilles!

Sure, I can take over maintenance for the project. I am still working on getting the test coverage up anyway and I will be using the sed.py in the StaSh project as well (a bash-like shell for the Pythonista-App that allows Python development on a phone or tablet - if you don’t know Pythonista yet, it is definitely worth looking at!)

As for timings... it should be slower in compiling the script, since I am doing a lot more than before. For running the script it might be faster due to the very specialized address range objects but than again, using a lot of s commands might be slower due to the fact that I have to process the replacement string a lot more than before...

Other than that, the execution part of the project didn’t change much.

I am looking into optimizing the labels out of the processing as well as the block-ends, but that will only marginally help.

Since it is only my second bigger Python project you might find a few things that could be done better or more Python-like. ;-) I am still learning as well.

As for the coding style: I never liked putting spaces around operators. In my view that pulls the code to much apart. I find it a lot easier to distinguish expressions from the rest of the code line, if they are compact and not broken into pieces. Also for parentheses... I am only using them where they will help with making things easier to grasp if they aren’t strictly required. But I‘ll run pep8 and pylint myself and look if there are things I can improve. I definitely forgot to get rid of the trailing spaces, though. :-(

Is there any material on your website, that should be pulled into the project, since I would not be able to maintain it there?

Frank

**Comment by GillesArcas** [comment]
Hi Frank,
great you take the lead on that. I have added a note redirecting to your repository at the top of the original readme file. This allows me to close the pull request. Regarding style, I would advice to stick with python standards. Spacing is just a matter of habit and respecting the standard will make any python programmer more comfortable. But, hey, it is just yours now. Keep up the good work!
Gilles
PS: after checking, it appears that pep8 module (renamed to pycodestyle) does accept x  = 2*a+1 (but not x=2*a+1 neither if x==a:) There is always something to learn :)

**Pull request closed without merging**
